### ISSUE TITLE
Really slow

### ISSUE THREAD

**Issue by simkessy** [jimeh/git-aware-prompt#22] opened 2015-07-01 18:14 UTC
Hey, 

I just implemented this in a vagrant box and it works perfectly but it's really slow. I even removed the git_dirty from PS1 but that didn't improve things much. 

This is what my prompt looks like: 

`export PS1="\${debian_chroot:+(\$debian_chroot)}\[$txtgrn\]@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] \[$txtylw\]\$git_branch\[$txtrst\]\$ "`

**Comment by michaelachrisco** [comment] 2015-09-24 21:50
Is `git status` also slow? I had this same issue when running the script as .bashrc. 
What does:
`time git rev-parse --abbrev-ref HEAD`
and 
`time git status --porcelain`
look like @simkessy?

**Comment by joeytwiddle** [comment] 2015-09-24 22:08
If you are suffering from a slow prompt, you might like to try [my fork](https://github.com/joeytwiddle/git-aware-prompt). If the git status process takes to long, then it aborts to give you a prompt, but continues processing in the background, so you can get the stats later. It's probably not for everyone, but maybe it can help you.

**Comment by michaelachrisco** [comment] 2015-09-24 22:11
Interesting, Ill have to give your fork a try. I like the fact that it starts the git status --porcelain in the background. :+1:

**Comment by joeytwiddle** [comment] 2015-09-27 13:31
This issue seems like a duplicate of #9

**Comment by jimeh** [comment] 2015-10-16 11:22
This does in indeed look like a duplicate of #9.

**Closed by jimeh** 2015-10-16 11:22 UTC
